### ISSUE TITLE
http proxy settings not used in container

### ISSUE THREAD

**Issue by amaltson** [pivotal-cf/micropcf#9]
I'm trying to spin up a `micropcf`, but we're behind an HTTP proxy. I noticed with the released Vagrant file that it's using the same setup as Lattice with regards to the `vagrant-proxyconf` plugin. I vagrant up the machine with `http_proxy` and `https_proxy` exported, and find that `micropcf` starts correctly and when I `vagrant ssh` the proxy settings are set.

```
vagrant@micropcf:~$ echo $http_proxy
http://proxy:3128
vagrant@micropcf:~$ echo $https_proxy
http://proxy:3128
vagrant@micropcf:~$ echo $no_proxy
localhost,127.0.0.1,192.168.11.11,local.micropcf.io
```

I've also left the http(s) proxy and no_proxy settings on my Mac too before pushing.

```
arthur@hephaestus $ echo $http_proxy
http://proxy:3128
arthur@hephaestus $ echo $https_proxy
http://proxy:3128
arthur@hephaestus $ echo $no_proxy
localhost,127.0.0.1,192.168.11.11,local.micropcf.io
```

But when I push up the application, which is just a simple Ruby app, it fails to download bundler. But I can download bundler from the VM itself:

```
vagrant@micropcf:~$ wget https://pivotal-buildpacks.s3.amazonaws.com/ruby/binaries/shared/bundler-1.9.7.tgz
--2015-12-14 21:21:19--  https://pivotal-buildpacks.s3.amazonaws.com/ruby/binaries/shared/bundler-1.9.7.tgz
Resolving monty.ms.otpp.net (monty.ms.otpp.net)... 10.254.204.104, 10.254.204.104
Connecting to monty.ms.otpp.net (monty.ms.otpp.net)|10.254.204.104|:3128... connected.
Proxy request sent, awaiting response... 200 OK
Length: 244764 (239K) [binary/octet-stream]
Saving to: ‘bundler-1.9.7.tgz’

100%[====================================================================================================================================================================================================================================>] 244,764     --.-K/s   in 0.1s

2015-12-14 21:21:20 (1.83 MB/s) - ‘bundler-1.9.7.tgz’ saved [244764/244764]
```

It just seems that the proxy settings aren't making their way to the garden containers. I poked around a bit to see where garden is being initialized, but I haven't found anything yet (no upstart/init script I can see).

Here's the full logs from the push:

```
arthur@hephaestus $ cf push badges
Creating app badges in org local.micropcf.io-org / space test as admin...
OK

Using route badges.local.micropcf.io
Binding badges.local.micropcf.io to badges...
OK

Uploading badges...
Uploading app files from: /Users/arthur/work/ruby/badges
Uploading 10.9K, 21 files
Done uploading
OK

Starting app badges in org local.micropcf.io-org / space test as admin...
Creating container
Successfully created container
Downloading app package...
Downloaded app package (7.2K)
No buildpack specified; fetching standard buildpacks to detect and build your application.
Downloading buildpacks (ruby_buildpack, nodejs_buildpack, go_buildpack, python_buildpack, php_buildpack, staticfile_buildpack, binary_buildpack, java_buildpack)...
Downloading python_buildpack...
Downloading nodejs_buildpack...
Downloading php_buildpack...
Downloading ruby_buildpack...
Downloaded ruby_buildpack
Downloading go_buildpack...
Downloaded php_buildpack
Downloading staticfile_buildpack...
Downloaded python_buildpack
Downloading binary_buildpack...
Downloaded staticfile_buildpack
Downloading java_buildpack...
Downloaded binary_buildpack
Downloaded java_buildpack
Downloaded nodejs_buildpack
Downloaded go_buildpack
Downloaded buildpacks
Staging...
cat: ../VERSION: No such file or directory
-------> Buildpack version 1.6.9
       Downloaded [https://pivotal-buildpacks.s3.amazonaws.com/ruby/binaries/shared/bundler-1.9.7.tgz]
 !
/tmp/buildpacks/3de781907107e5d281f03f8dc06414be/lib/language_pack/shell_helpers.rb:50:in `run!': Command: 'set -o pipefail; curl --fail --retry 3 --retry-delay 1 --connect-timeout 10 --max-time 90 https://pivotal-buildpacks.s3.amazonaws.com/ruby/binaries/shared/bundler-1.9.7.tgz -s -o - | tar zxf - ' failed unexpectedly: (LanguagePack::Fetcher::FetchError)
 !     Command: 'set -o pipefail; curl --fail --retry 3 --retry-delay 1 --connect-timeout 10 --max-time 90 https://pivotal-buildpacks.s3.amazonaws.com/ruby/binaries/shared/bundler-1.9.7.tgz -s -o - | tar zxf - ' failed unexpectedly:
 !
 !     gzip: stdin: unexpected end of file
 !     tar: Child returned status 1
 !     tar: Error is not recoverable: exiting now
 !
gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
        from /tmp/buildpacks/3de781907107e5d281f03f8dc06414be/lib/language_pack/fetcher.rb:24:in `fetch_untar'
        from /tmp/buildpacks/3de781907107e5d281f03f8dc06414be/lib/language_pack/helpers/bundler_wrapper.rb:118:in `block (2 levels) in fetch_bundler'
        from /tmp/buildpacks/3de781907107e5d281f03f8dc06414be/lib/language_pack/helpers/bundler_wrapper.rb:117:in `chdir'
        from /tmp/buildpacks/3de781907107e5d281f03f8dc06414be/lib/language_pack/helpers/bundler_wrapper.rb:117:in `block in fetch_bundler'
        from /tmp/buildpacks/3de781907107e5d281f03f8dc06414be/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
        from /tmp/buildpacks/3de781907107e5d281f03f8dc06414be/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
        from /tmp/buildpacks/3de781907107e5d281f03f8dc06414be/lib/language_pack/instrument.rb:17:in `block in instrument'
        from /usr/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
        from /tmp/buildpacks/3de781907107e5d281f03f8dc06414be/lib/language_pack/instrument.rb:16:in `instrument'
        from /tmp/buildpacks/3de781907107e5d281f03f8dc06414be/lib/language_pack/helpers/bundler_wrapper.rb:84:in `instrument'
        from /tmp/buildpacks/3de781907107e5d281f03f8dc06414be/lib/language_pack/helpers/bundler_wrapper.rb:114:in `fetch_bundler'
        from /tmp/buildpacks/3de781907107e5d281f03f8dc06414be/lib/language_pack/helpers/bundler_wrapper.rb:33:in `install'
        from /tmp/buildpacks/3de781907107e5d281f03f8dc06414be/lib/language_pack/ruby.rb:32:in `bundler'
        from /tmp/buildpacks/3de781907107e5d281f03f8dc06414be/lib/language_pack/rails5.rb:9:in `block in use?'
        from /tmp/buildpacks/3de781907107e5d281f03f8dc06414be/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
        from /tmp/buildpacks/3de781907107e5d281f03f8dc06414be/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
        from /tmp/buildpacks/3de781907107e5d281f03f8dc06414be/lib/language_pack/instrument.rb:17:in `block in instrument'
        from /usr/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
        from /tmp/buildpacks/3de781907107e5d281f03f8dc06414be/lib/language_pack/instrument.rb:16:in `instrument'
        from /tmp/buildpacks/3de781907107e5d281f03f8dc06414be/lib/language_pack/base.rb:48:in `instrument'
        from /tmp/buildpacks/3de781907107e5d281f03f8dc06414be/lib/language_pack/rails5.rb:8:in `use?'
        from /tmp/buildpacks/3de781907107e5d281f03f8dc06414be/lib/language_pack.rb:17:in `block (2 levels) in detect'
        from /tmp/buildpacks/3de781907107e5d281f03f8dc06414be/lib/language_pack.rb:16:in `each'
        from /tmp/buildpacks/3de781907107e5d281f03f8dc06414be/lib/language_pack.rb:16:in `detect'
        from /tmp/buildpacks/3de781907107e5d281f03f8dc06414be/lib/language_pack.rb:16:in `block in detect'
        from /tmp/buildpacks/3de781907107e5d281f03f8dc06414be/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
        from /tmp/buildpacks/3de781907107e5d281f03f8dc06414be/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
        from /tmp/buildpacks/3de781907107e5d281f03f8dc06414be/lib/language_pack/instrument.rb:17:in `block in instrument'
        from /usr/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
        from /tmp/buildpacks/3de781907107e5d281f03f8dc06414be/lib/language_pack/instrument.rb:16:in `instrument'
        from /tmp/buildpacks/3de781907107e5d281f03f8dc06414be/lib/language_pack.rb:13:in `detect'
        from /tmp/buildpacks/3de781907107e5d281f03f8dc06414be/bin/compile:19:in `block in <main>'
        from /tmp/buildpacks/3de781907107e5d281f03f8dc06414be/lib/language_pack/instrument.rb:35:in `call'
        from /tmp/buildpacks/3de781907107e5d281f03f8dc06414be/lib/language_pack/instrument.rb:35:in `block in trace'
        from /tmp/buildpacks/3de781907107e5d281f03f8dc06414be/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
        from /tmp/buildpacks/3de781907107e5d281f03f8dc06414be/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
        from /tmp/buildpacks/3de781907107e5d281f03f8dc06414be/lib/language_pack/instrument.rb:17:in `block in instrument'
        from /usr/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
        from /tmp/buildpacks/3de781907107e5d281f03f8dc06414be/lib/language_pack/instrument.rb:16:in `instrument'
        from /tmp/buildpacks/3de781907107e5d281f03f8dc06414be/lib/language_pack/instrument.rb:35:in `trace'
        from /tmp/buildpacks/3de781907107e5d281f03f8dc06414be/bin/compile:18:in `<main>'
Failed to compile droplet
Exit status 223
Staging failed: Exited with status 223

FAILED
BuildpackCompileFailed
```

**Comment by davidwadden** [comment]
@amaltson  i'm not surprised at this.  lattice had custom logic around passing the cluster proxy configuration to the CLI so it could set environment variables appropriately during staging and app runtime.  now we're relying on `cf`, and it's probably an atypical configuration to put a CF behind a proxy.

i don't have an estimate when we'll get to look at this with the holidays coming up, but we'll start looking into proxy support on microPCF.

**Comment by amaltson** [comment]
@davidwadden I've found that if I upload the offline buildpack into microPCF it actually works fine. Thanks!

**Comment by amaltson** [comment]
I'll leave the issue open to track proxy work on microPCF.

**Comment by davidwadden** [comment]
i'm going to go ahead and close this for now as we're not considering proxy support in the near term.  instead, we're looking to make MicroPCF match PCF, so we'll probably address working offline (all the buildpacks are currently offline already) before supporting proxies.

**Comment by amaltson** [comment]
Sounds good, offline buildpacks work great.
